const form = document.getElementById("healthForm");
const resultBox = document.getElementById("result");
const errorBox = document.getElementById("errorBox");
const riskBadge = document.getElementById("riskBadge");
const explanationText = document.getElementById("explanationText");
const sourceNote = document.getElementById("sourceNote");

form.addEventListener("submit", async (e) => {
  e.preventDefault();
  errorBox.classList.add("hidden");
  resultBox.classList.add("hidden");

  const submitBtn = form.querySelector("button");
  submitBtn.disabled = true;
  submitBtn.textContent = "Analysing...";

  const formData = new FormData(form);
  const payload = {};
  for (const [key, value] of formData.entries()) payload[key] = value;

  try {
    const res = await fetch("/predict", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    const data = await res.json();

    if (!res.ok) throw new Error(data.error || "Something went wrong.");

    const levelClass = { Low: "risk-low", Moderate: "risk-moderate", High: "risk-high" }[data.risk_level];
    riskBadge.textContent = `${data.risk_level} Risk — ${(data.risk_probability * 100).toFixed(1)}%`;
    riskBadge.className = `risk-badge ${levelClass}`;
    explanationText.textContent = data.explanation;
    sourceNote.textContent =
      data.explanation_source === "llm"
        ? "Explanation generated live by the GenAI module."
        : "Explanation generated by the built-in template (set ANTHROPIC_API_KEY on Render to enable live GenAI).";

    resultBox.classList.remove("hidden");
  } catch (err) {
    errorBox.textContent = err.message;
    errorBox.classList.remove("hidden");
  } finally {
    submitBtn.disabled = false;
    submitBtn.textContent = "Get Risk Assessment";
  }
});
